#spring.application.name=springbootRabbitMQ

spring:
  application:
    name: springbootRabbitMQ
  datasource:
    url: jdbc:mysql://docker-mysql:3306/test
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 6be7b0bd588d81
    password: 39c49cb87d598c
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

server:
  port: 9091

application:
  mail:
    sent:
      from: no-reply@food.com

rabbitmq:
  queue:
    email:
      name: email_queue
  exchange:
    email:
      name: email_exchange
  binding:
    email:
      name: email_routing_key